<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text9_text9</name>
   <tag></tag>
   <elementGuidId>701213e7-dbd8-40e5-83cf-bf0abde57970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00d9a253-823e-4dbe-8210-220c4f1b88ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1502dd42-baa5-47e6-be74-f8524ebdd45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text9</value>
      <webElementGuid>b70a349c-72ba-4003-9f50-9fef5b6ad497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text9&quot;)</value>
      <webElementGuid>fa8a3c3f-93eb-49fe-bd70-1a70d908af34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text9']</value>
      <webElementGuid>5c66440e-94eb-4807-a7b9-a4fc5c08f3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>129dd61e-ca38-43be-9ac6-c48e2051270c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text9']</value>
      <webElementGuid>073605a9-c837-46bb-a6a1-28b4c7ba127b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
