<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text16_text16</name>
   <tag></tag>
   <elementGuidId>c1c2077f-1544-4ff1-8c3b-916096b24963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79dec8fa-9184-4625-93b5-e56d53b1fcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d61c6d2f-3212-4acd-bbed-843c8390394e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text16</value>
      <webElementGuid>1c203d02-26a2-4ce5-8bcd-4269697f1f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text16&quot;)</value>
      <webElementGuid>9e753352-d9ba-4958-94c7-a83a99fbfde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text16']</value>
      <webElementGuid>f6ebd2ae-32cf-457b-b789-db95472ac808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[16]</value>
      <webElementGuid>35f2c53b-e61e-48b2-af78-083e3b90cb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text16']</value>
      <webElementGuid>c796aa2a-f230-401a-a833-c0b1f61fa07b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
