<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text11_text11</name>
   <tag></tag>
   <elementGuidId>2400e747-f7db-4d83-b083-bc74c1536fcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0da22c5-6878-4e72-b5cb-ef96ab432c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3aab43d0-a327-4c84-8fac-3bbe3436eed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text11</value>
      <webElementGuid>0faa5cd9-8552-4118-91b4-2a91fb3227be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text11&quot;)</value>
      <webElementGuid>4a9d30dc-228c-41ce-b9f0-1617180bbe09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text11']</value>
      <webElementGuid>7105d1bc-7c3d-4a72-94d4-0f2a3e374d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>fef6d1a1-2b23-4c13-bbc6-b927f7303a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text11']</value>
      <webElementGuid>76d71b50-9dbc-4ae2-b15f-0a29f4e987c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
