<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text37_text37</name>
   <tag></tag>
   <elementGuidId>df59a738-cee7-4e5b-a5aa-08d5d058565b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text37</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text37']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d50d9a12-7698-4f1f-a6f3-41b90c9211d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5eb5a882-7603-47e8-b547-fab8c8c6dd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text37</value>
      <webElementGuid>ef9aa0e1-d566-4881-997b-df663cbfbb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text37&quot;)</value>
      <webElementGuid>369b6153-d86c-4871-86a5-e64315b4683a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text37']</value>
      <webElementGuid>3fd0babc-3ea8-484f-932b-b309ad2eba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[37]</value>
      <webElementGuid>f4fbe731-a47b-4b56-88bd-ee51097563f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text37']</value>
      <webElementGuid>6ea88fa8-a395-4a15-8fce-4b4ab29e9972</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
