<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text22_text22</name>
   <tag></tag>
   <elementGuidId>048e7deb-4ad2-4c4a-872e-d63acd98e4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c95378f-b958-461d-b70c-5c89c1f9ffff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af4f32a4-cec5-4a04-b5f5-b0140d23bb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text22</value>
      <webElementGuid>fabea6b0-e53a-4eb7-96ff-6f3b9f4b3460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text22&quot;)</value>
      <webElementGuid>a5751418-3e39-4373-a10a-cb5d4818bdd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text22']</value>
      <webElementGuid>38c9a41f-9d58-46de-9bff-0a16e4af6310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[22]</value>
      <webElementGuid>b17a0319-82c1-4e4a-86ac-a1ae692aa712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text22']</value>
      <webElementGuid>54d02ab5-c877-435e-85e8-52287bd7c6fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
