<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text13_text13</name>
   <tag></tag>
   <elementGuidId>795784ea-0b78-4ab3-93dd-d411b7049c31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text13</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04f12292-4a77-42d9-8bb0-8d13eabebbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c57abc70-716b-4f42-974e-ab1a9d2f13aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text13</value>
      <webElementGuid>8c4992e2-8706-4c64-b5b8-84d7b2440b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text13&quot;)</value>
      <webElementGuid>20397090-3e3b-4312-86be-89dcd5566346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text13']</value>
      <webElementGuid>c0532262-a241-48ee-b273-4134bcbd0c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[13]</value>
      <webElementGuid>a91cb5fb-72de-4521-a2bb-2960169024a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text13']</value>
      <webElementGuid>7cadd12b-5cc8-4cec-a062-e6c90a288dab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
