<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text1_text1</name>
   <tag></tag>
   <elementGuidId>53b19fff-4f57-486c-8d56-8f8faaaf89d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf66dae1-9723-4515-aa07-0a48deacd489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a03e481b-ab8e-4651-8b88-054c7df9491f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text1</value>
      <webElementGuid>e2c1c491-bdac-46de-83a0-ae9ae0dbb48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text1&quot;)</value>
      <webElementGuid>e145c371-5634-420c-86b9-e5508774ba52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text1']</value>
      <webElementGuid>2a19edad-61ea-447f-ac84-ef1f9dc2efab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fd658723-225b-4386-8eda-98db0016531f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text1']</value>
      <webElementGuid>76c16572-a012-40d3-b876-632a25430d4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
