<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text12_text12</name>
   <tag></tag>
   <elementGuidId>1b83c4ef-1760-4a84-9995-7dad59a92b7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>640b352a-b44c-44e8-b43f-266bc92918ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dee6026-8b0b-420e-b0c4-663e000727fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text12</value>
      <webElementGuid>e0c5c356-5319-493f-a3c7-5a25e90ac888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text12&quot;)</value>
      <webElementGuid>c91fc7c2-36b4-46a1-94f9-91583cd69299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text12']</value>
      <webElementGuid>bcc459ee-71b8-4026-8383-7ea677d1077c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[12]</value>
      <webElementGuid>8fd9814e-874a-4ea1-8211-f32f17b5c343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text12']</value>
      <webElementGuid>b63551bf-943b-4b0d-a363-376417c77b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
