<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text29_text29</name>
   <tag></tag>
   <elementGuidId>0479415c-9fd5-4bf2-ad32-a03b9cd8493a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c900aa6a-2587-46dc-93c2-25328edf1ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa92f331-75d8-42ce-8c9f-bf544d42f34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text29</value>
      <webElementGuid>dd9570e3-d5e5-4aef-9cb2-412367f352b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text29&quot;)</value>
      <webElementGuid>bd67f046-afcc-41c1-aeec-9eead1ff8826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text29']</value>
      <webElementGuid>ddef0bc6-40ab-4fcf-83b9-d85e7f15d892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>d0d94472-84cd-4657-b3dd-9aa0ce154e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text29']</value>
      <webElementGuid>14301a4a-dcf5-4745-9b67-6f6d96ad724b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
