<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text40_text40</name>
   <tag></tag>
   <elementGuidId>96d9b0fb-2d80-4a8a-92ae-cde15f5a5246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text40</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text40']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ac8274f-969d-421c-bda1-7a476b4e5cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bbc6620-0caa-4b6f-ab34-3edec16fd42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text40</value>
      <webElementGuid>4288219e-df8b-428c-86e7-d1d11a547160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text40&quot;)</value>
      <webElementGuid>89c4dcc8-0b6e-4695-9068-9d8970e88ef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text40']</value>
      <webElementGuid>47777fb9-5e2d-477d-a8eb-88769b8beb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[40]</value>
      <webElementGuid>6554a220-75a6-43cf-b115-a94b2d7c29db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text40']</value>
      <webElementGuid>bac4b0f9-e1a3-401c-a647-34b0efff1cae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
