<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text26_text26</name>
   <tag></tag>
   <elementGuidId>ac877e74-f7e1-4f7f-8335-1f84bb974850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cb34860-ce8f-4718-9ea8-0582596f41db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca00c598-2d80-4f59-b0fd-07962ae86fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text26</value>
      <webElementGuid>e7312250-bbd4-46c3-bd4c-be82a6eea185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text26&quot;)</value>
      <webElementGuid>42015fb3-b94a-47f3-ad0c-0f7e3d0a1cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text26']</value>
      <webElementGuid>262f6b5b-3803-4e9d-ba0a-75e9d3f867f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[26]</value>
      <webElementGuid>fc2d228e-8141-4868-9203-edc135f38913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text26']</value>
      <webElementGuid>7a45f220-bf0e-4055-a8cf-048c55752633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
