<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text21_text21</name>
   <tag></tag>
   <elementGuidId>4219ab14-1999-4d8b-98df-5bb5f4b2e63a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cbb8307-0a98-4d57-95c4-9e875c6e2826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ca49e10-56d8-4a24-96a3-9b4e52b2ce85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text21</value>
      <webElementGuid>46769060-21b8-4d40-a283-9c237d8ac278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text21&quot;)</value>
      <webElementGuid>e6baf240-ea9f-4eb4-9a69-c39c67642834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text21']</value>
      <webElementGuid>8f367ecd-61cd-4807-a691-2af11fd070b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[21]</value>
      <webElementGuid>e6647fe3-c167-4392-b8cd-92b0ba882868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text21']</value>
      <webElementGuid>555126b4-3f71-4997-a916-3b9ea4f57ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
