<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox8_checkbox9</name>
   <tag></tag>
   <elementGuidId>73fd3d75-c0cf-4ff2-9e9d-9efcf830cef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4a83604-0b09-4537-ab62-7fb48d9812a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a3a8e4eb-5a1c-45c4-a72f-ee0aad2227e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox9</value>
      <webElementGuid>cb0a9e1f-1fdb-459b-a4bc-5239dd61493d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkbox9</value>
      <webElementGuid>175045a1-5356-4870-9292-6b06a2066475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox9&quot;)</value>
      <webElementGuid>78527fd0-abfc-46ab-b470-8842594fd64a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox9']</value>
      <webElementGuid>eff4a3ec-3cb0-494c-9a65-d4795670202d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[19]</value>
      <webElementGuid>7595fbef-2965-43de-88ec-2cbe1cb77f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox9']</value>
      <webElementGuid>418b7c08-9d06-4023-a8f9-7ee09a2c6775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
