<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text3_text3</name>
   <tag></tag>
   <elementGuidId>a80b8b2e-437f-4186-9f39-54754660ada5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19d1202b-759b-49c7-9012-7e08c214ae9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffa5ca28-6466-48dc-819d-2d403cb17c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text3</value>
      <webElementGuid>71b1bb32-e2fc-45e0-9864-ecfb67d079cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text3&quot;)</value>
      <webElementGuid>3d4742ac-8635-45b7-890d-8f2f06245d03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text3']</value>
      <webElementGuid>4c824631-4a6e-4705-b9a0-07935fd89ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>088840a4-a3c1-4e58-8020-5c0c3cda6da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text3']</value>
      <webElementGuid>98e940c8-f92b-46c7-bde1-eca3ff534fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
