<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio1_radio2</name>
   <tag></tag>
   <elementGuidId>56abb07b-7e20-4b0f-a24c-50bc8adc1da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b558211-12b0-43b0-b746-41f33296910d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e496766c-41df-4914-b79d-5c4f07dfd2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio2</value>
      <webElementGuid>d54420e5-7670-4141-a9a2-ad39bf943433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio2</value>
      <webElementGuid>8bb4a0f8-b455-4291-9dc2-f33db47aab46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio2&quot;)</value>
      <webElementGuid>6e0b6c9a-ad4b-4cf7-a0cb-2ee2d859009f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio2']</value>
      <webElementGuid>b7f21cef-283e-4c75-9edc-adbc8ec70ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[22]</value>
      <webElementGuid>f09b389c-fac3-4849-9ad9-b1da4d13b0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio2']</value>
      <webElementGuid>10efc4eb-813d-41eb-b9d7-c9af509ac829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
