<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio6_radio7</name>
   <tag></tag>
   <elementGuidId>09b8b9f6-c574-49e2-bbd0-1da21ee56d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>526bc19a-229a-4b71-8b58-f90ad743d765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>794d3559-c77b-44d9-9b44-1077c03548c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio7</value>
      <webElementGuid>731caff6-1d1b-44af-9356-164b4da7080b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio7</value>
      <webElementGuid>8023c48f-0903-43b2-ae34-ef50c510cf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio7&quot;)</value>
      <webElementGuid>2a20f882-e056-4ebd-8907-065617939e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio7']</value>
      <webElementGuid>640f60dd-1892-4b1b-83d5-ec0470bdf11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>a59b756b-3ed0-43b0-bbe0-807d477cdf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio7']</value>
      <webElementGuid>1723728d-ac00-4efa-b1b2-d82130a16ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
