<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value1          value2          valu_9f7bd8_1</name>
   <tag></tag>
   <elementGuidId>2802a2c1-a7b5-4320-8ee0-a967ce7365cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cc1d0ed0-228f-4886-bcdb-0178b3c4eb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option2</value>
      <webElementGuid>0f2e8a40-3c2c-4752-9b2d-b47bb5179a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          value1
          value2
          value3
          value4
        </value>
      <webElementGuid>8dd86e54-d20e-4f60-8153-5a7d16f9f927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option2&quot;)</value>
      <webElementGuid>f797f2c3-eeab-4dfe-b090-74a68edf83e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option2']</value>
      <webElementGuid>35a63ac9-33f3-4fe9-ab6e-6d7bfd0da307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option2:'])[1]/following::select[1]</value>
      <webElementGuid>c9113c00-8964-47df-9c7a-68069c6c53ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option1:'])[1]/following::select[2]</value>
      <webElementGuid>c80ee3d1-63eb-40d9-8b3b-ef90306112e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option3:'])[1]/preceding::select[1]</value>
      <webElementGuid>b5cf8830-b1e0-4cc5-b36e-54b193059b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option4:'])[1]/preceding::select[2]</value>
      <webElementGuid>c5b12ef6-be09-44b7-ad31-a66311fcb085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>3731652a-1194-4c65-949a-3d00e65c88cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option2' and (text() = '
          value1
          value2
          value3
          value4
        ' or . = '
          value1
          value2
          value3
          value4
        ')]</value>
      <webElementGuid>08a2fb70-12ac-48e3-bbfb-e849d717dcf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
